on: [pull_request, push, merge_group]
name: ci
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  check-pr:
    name: validate commits
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
    - uses: actions/checkout@v6.0.2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0
    - run: git fetch origin main
    - uses: flux-framework/pr-validator@master

  spelling:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6.0.2
    - name: Check Spelling
      uses: crate-ci/typos@v1.44.0

  check-el9:
    name: el9 checks
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      TAP_DRIVER_QUIET: 1
      FLUX_TEST_TIMEOUT: 300
    steps:
    - uses: actions/checkout@v6.0.2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0
    - run: git fetch --tags || true
    - name: docker-run-checks
      timeout-minutes: 45
      run: src/test/docker/docker-run-checks.sh -j 4 -i el9 --

    - name: annotate errors
      if: failure() || cancelled()
      run: src/test/checks-annotate.sh

  check-focal:
    name: focal checks
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      TAP_DRIVER_QUIET: 1
      FLUX_TEST_TIMEOUT: 300
    steps:
    - uses: actions/checkout@v6.0.2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0
    - run: git fetch --tags || true
    - name: docker-run-checks
      timeout-minutes: 45
      run: src/test/docker/docker-run-checks.sh -j 4 -i focal --

    - name: annotate errors
      if: failure() || cancelled()
      run: src/test/checks-annotate.sh
